LOG_VERBOSE=true

# Web Server
WEB_SERVER_ENABLED=true
WEB_HOST="localhost"
WEB_PORT=8081

# DB
DB_ENABLED=true
DB_HOST="ec2-52-7-168-69.compute-1.amazonaws.com"
DB_USER="gzjdpqnsypiqvy"
DB_PORT=5432
DB_NAME="d3jqadkmp4d3i"
DB_PASSWORD="b1b2e1490b00f0fca146936ec634bb2465b902dca6809c497857b87c6425a138"